config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # get "/field_histories", to: "field_histories#index"

  resources :tickets
  resources :vocabulary_histories

  resources :vocabularies
  resources :retailers do
    resources :field_histories
    resources :fields, shallow: true do
      resources :variations, shallow: true
    end#, shallow: true # частичная вложенность только для index create new
    resources :comments
  end
  root 'retailers#index'
end

app/models/variation.rb
class Variation < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { scope: :field_id }
  has_rich_text :description

  belongs_to :field
  belongs_to :user
end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variation, only: %i[ show edit update destroy ]
  before_action :set_field, only: %i[ new create ]
  before_action :check_role, only: %i[ new show edit ]

  # GET /variations or /variations.json
  def index
    @variations = Variation.all
  end

  # GET /variations/1 or /variations/1.json
  def show
  end

  # GET /variations/new
  def new
    @variation = Variation.new
  end

  # GET /variations/1/edit
  def edit
  end

  # POST /variations or /variations.json
  def create
    @variation = @field.variations.new(variation_params.merge(user_id: current_user.id))
    if @variation.save
      FieldHistory.new(variation_history_params).save!
      redirect_to @field.retailer
    else
      render :new
    end
  end

  # PATCH/PUT /variations/1 or /variations/1.json
  def update
    respond_to do |format|
      if @variation.update(variation_params)
        FieldHistory.new(variation_history_params(_update: true)).save!
        format.html { redirect_to @variation.field.retailer, :"data-turbolinks" => "false", notice: "Вариация была успешно обновлена." }
        format.json { render :show, status: :ok, location: @variation.field.retailer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variations/1 or /variations/1.json
  def destroy
    FieldHistory.new(variation_history_params(_destroy: @variation.name)).save!
    @variation.destroy
    respond_to do |format|
      format.html { redirect_to @variation.field.retailer, notice: "Вариация была успешна удалена." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation
      @variation = Variation.find(params[:id])
    end

    def set_field
      @field = Field.find(params[:field_id])
    end

    def check_role
      respond_to { |format| format.html { redirect_to @field&.retailer || @variation.field.retailer, alert: "У вас нету доступа к просмотру содержимого этой страницы" } } unless ["QA","admin"].include? current_user.role
    end

    def variation_history_params(_destroy: false, _update: false)
        return {
          field_id: @variation[:field_id],
          retailer_id: @variation.field.retailer_id,
          fields_title: @variation&.field.title,
          variation_name: "Вариация #{_destroy} - удалена",
          description: "Вариация #{_destroy} - удалена",
          vocabulary_name: "Вариация #{_destroy} - удалена",
          user_id: current_user.id
        } if _destroy

        return {
          field_id: @variation[:field_id],
          retailer_id: @variation.field.retailer_id,
          fields_title: @variation.field.title,
          variation_name: @variation.name,
          description: @variation.description,
          vocabulary_name: @variation.field.vocabulary.name,
          user_id: current_user.id
        } if _update

        {
          field_id: @variation[:field_id],
          retailer_id: @variation.field.retailer_id,
          fields_title: @variation.field.title,
          variation_name: "Создана новая вариация: #{@variation.name}",
          description: @variation.description,
          vocabulary_name: @variation.field.vocabulary.name,
          user_id: current_user.id
        }
      end

    # Only allow a list of trusted parameters through.
      def variation_params
        params.require(:variation).permit(:name, :description)
      end
end

app/helpers/variations_helper.rb
module VariationsHelper
end

app/views/variations/_form.html.erb
<%= form_for [@field, @variation] do |f| %>
  <% if @variation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variation.errors.count, "ошибка") %> препятствует сохранению:</h2>

      <ul>
        <% @variation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Название" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description, "Описание" %>
    <%= f.rich_text_area :description %>
  </div>

  <div class="field">
    <%= f.submit "#{@variation.new_record? ? 'Создать' : 'Обновить' }", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/variations/edit.html.erb
<div class="container">
  <h1>Редактирование вариации</h1>

  <%= render 'form', variation: @variation %>

  <%= link_to 'Назад', retailer_path(@variation.field.retailer), :"data-turbolinks" => "false", class: "btn btn-secondary" %>
</div>

app/views/variations/index.html.erb
<h1>Variations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variations.each do |variation| %>
      <tr>
        <td><%= variation.name %></td>
        <td><%= variation.description %></td>
        <td><%= link_to 'Показать', variation, class: "btn btn-secondary" %></td>
        <td><%= link_to 'Изменить', edit_variation_path(variation), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Удалить', variation, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variation', new_variation_path %>

app/views/variations/new.html.erb
<div class="container">
  <h1>Новая вариация для <%= @field.title %></h1>
  <%= render 'form', variation: @variation %>

  <%= link_to 'Назад', @field.retailer, :"data-turbolinks" => "false", class: "btn btn-secondary" %>
</div>

app/views/variations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @variation.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @variation.description %>
</p>

<%= link_to 'Изменить', edit_variation_path(@variation), class: "btn btn-secondary" %></br
<%= link_to 'Назад', field_path(@variation.field_id), :"data-turbolinks" => "false" %>