config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # get "/field_histories", to: "field_histories#index"

  resources :tickets
  resources :vocabulary_histories

  resources :vocabularies
  resources :retailers do
    resources :field_histories
    resources :fields, shallow: true do
      resources :variations, shallow: true
    end#, shallow: true # частичная вложенность только для index create new
    resources :comments
  end
  root 'retailers#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, allow_blank: false

  belongs_to :user
  belongs_to :retailer

  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @retailer = Retailer.find(params[:retailer_id])
    @comment = @retailer.comments.new({parent_id: params[:parent_id]}.merge(user_id: current_user.id))
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @retailer = Retailer.find(params[:retailer_id])
    @comment = @retailer.comments.new(comment_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @retailer, notice: "Коментарий был успешно создан." }
        format.json { render :show, status: :created, location: @retailer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Коментарий был успешно обновлен." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Коментарий был успешно удален." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :retailer_id, :parent_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %>
  <div class="card">
    <div class="card-body">
      <%= comment.body %>
      -
      <%= comment.user.email %>
      <%= link_to 'ответить', new_retailer_comment_path(@retailer, parent_id: comment.id), remote: true, class: 'd-block ' %>
    </div>
    <% if comment.replies.any? %>
      <% comment.replies.each do |reply| %>
        <%= render partial: 'comments/reply', locals: { reply: reply } %>
      <% end %>
    <% end %>

  </div>
  <div id="reply-form-<%= comment.id %>"></div>

<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "ошибка") %> препятствует сохранению:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :retailer_id %>
    <%= form.number_field :retailer_id %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= reply.body %>
    -
    <%= reply.user.email %>
    <%= link_to 'ответить', new_retailer_comment_path(@retailer, parent_id: reply.id), remote: true, class: 'd-block ' %>
  </div>
  <% if reply.replies.any? %>
    <% reply.replies.each do |reply_another| %>
      <%= render partial: 'comments/reply', locals: { reply: reply_another } %>
    <% end %>
  <% end %>
</div>
<div id="reply-form-<%= reply.id %>"></div>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@retailer, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Ответ' %>
        <%= f.text_area :body, class: 'form-control', required: "required" %>
      </div>
      <%= f.submit 'Отправить', class: 'btn btn-primary' %>
      <%= link_to 'Отмена', retailer_path(@retailer), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Показать', @comment, class: "btn btn-secondary" %> |
<%= link_to 'Назад', comments_path, class: "btn btn-secondary" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Retailer</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.retailer_id %></td>
        <td><%= comment.parent_id %></td>
        <td><%= link_to 'Показать', comment, class: "btn btn-secondary" %></td>
        <td><%= link_to 'Изменить', edit_comment_path(comment), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Удалить', comment, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Назад', comments_path %>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Retailer:</strong>
  <%= @comment.retailer_id %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @comment.parent_id %>
</p>

<%= link_to 'Изменить', edit_comment_path(@comment), class: "btn btn-secondary" %></br>
<%= link_to 'Назад', comments_path %>