config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # get "/field_histories", to: "field_histories#index"

  resources :tickets
  resources :vocabulary_histories

  resources :vocabularies
  resources :retailers do
    resources :field_histories
    resources :fields, shallow: true do
      resources :variations, shallow: true
    end#, shallow: true # частичная вложенность только для index create new
    resources :comments
  end
  root 'retailers#index'
end

app/models/field_history.rb
class FieldHistory < ApplicationRecord

  has_rich_text :description

  belongs_to :field
  belongs_to :retailer
  belongs_to :user

  before_create :tag_version_number

  private

  def tag_version_number
    self.version = generate_version_number
  end

  def generate_version_number
    (self.class.where(field_id: field_id)
         .maximum(:version) || 0) + 1
  end
end

app/controllers/field_histories_controller.rb
class FieldHistoriesController < ApplicationController
  before_action :set_field_history, only: %i[ show update destroy ]
  before_action :set_field, only: %i[ update ]

  # GET /field_histories or /field_histories.json
  def index
    @retailer = Retailer.find(params[:retailer_id])
    # @field_histories = FieldHistory.all.order(updated_at: :desc)
  end

  # GET /field_histories/1 or /field_histories/1.json
  def show
  end

  # POST /field_histories or /field_histories.json
  def create
    @field_history = FieldHistory.new(field_history_params)

    respond_to do |format|
      if @field_history.save
        format.html { redirect_to @field_history, notice: "История поля была успешно создан." }
        format.json { render :show, status: :created, location: @field_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @field_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_histories/1 or /field_histories/1.json
  def update
    restore_history_content
  end

  def restore_history_content
    respond_to do |format|
      binding.pry
      if @field.update(history_restored_params)
        FieldHistory.new(field_history_restored_params).save!
        format.html { redirect_to retailer_path(@field.retailer_id), notice: "Поле успешно возвращено из истори." }
        format.json { render :show, status: :ok, location: retailer_path(@field.retailer_id) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_history
      @field_history = FieldHistory.find(params[:id])
    end

    def set_field
      @field = Field.find(@field_history[:field_id])
    end

    def set_variation
      @variation = Variation.find(@field_history[:variation_id])
    end

    # Only allow a list of trusted parameters through.
    def field_history_params
      params.require(:field_history).permit(:fields_title, :variation_name, :description, :version)
    end

    def history_restored_params
      {
        title: @field_history.fields_title,
        description: @field_history.description,
      }
    end

    def field_history_restored_params
      {
        field_id: @field[:id],
        retailer_id: @field.retailer_id,
        fields_title: @field.vocabulary.spec_name,
        variation_name: nil,
        description: nil,
        vocabulary_name: @field.vocabulary.name,
        user_id: current_user.id
      }
    end
end

app/helpers/field_histories_helper.rb
module FieldHistoriesHelper
end

app/views/field_histories/_form.html.erb
<%= form_with(model: field_history) do |form| %>
  <% if field_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(field_history.errors.count, "ошибка") %> препятствует сохранению:</h2>

      <ul>
        <% field_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fields_title %>
    <%= form.text_field :fields_title %>
  </div>

  <div class="field">
    <%= form.label :variation_name %>
    <%= form.text_field :variation_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :verstion %>
    <%= form.number_field :verstion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/field_histories/edit.html.erb
<h1>Editing Field History</h1>

<%= render 'form', field_history: @field_history %>

<%= link_to 'Показать', @field_history, class: "btn btn-secondary" %> |
<%= link_to 'Назад', field_histories_path, class: "btn btn-secondary" %>

app/views/field_histories/index.html.erb
<span class="elem_with_icon">
  <i class="material-icons">article</i>
  <%= link_to 'Ретейлеры', @retailer %></br>
</span>

<h1>История изменения полей</h1>

<table>
  <thead>
    <tr>
      <th>Дата</th>
      <th>Ретейлер</th>
      <th>Наименование поля</th>
      <th>Вариация</th>
      <th>Описание</th>
      <th>Вокабуляр</th>
      <th>Пользователь</th>
      <th>Версия</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @retailer.field_histories.order(id: :desc).each do |field_history| %>
      <tr>
        <td><%= field_history.updated_at %></td>
        <td><%= field_history.retailer.title %></td>
        <td><%= field_history.fields_title %></td>
        <td><%= field_history.variation_name %></td>
        <td><%= field_history.description %></td>
        <td><%= field_history.vocabulary_name %></td>
        <td><%= field_history.user.email %></td>
        <td><%= field_history.version %></td>
        <td><%= field_history.field.nil? ? "" : (link_to 'Показать', retailer_field_history_path(@retailer.id, field_history.id), class: "btn btn-secondary") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/field_histories/new.html.erb
<h1>New Field History</h1>

<%= render 'form', field_history: @field_history %>

<%= link_to 'Назад', field_histories_path %>

app/views/field_histories/show.html.erb
<span class="elem_with_icon">
  <i class="material-icons">article</i>
  <%= link_to "Ретейлер #{@field_history.retailer.title}", retailer_path(@field_history.retailer_id) %>
</span>
<span class="elem_with_icon">
  <i class="material-icons">bookmark</i>
  <%= link_to "Поле #{@field_history.fields_title}", field_path(@field_history.field_id) %>
</span>


<table>
  <thead>
  <tr>
    <th>Версия </th>
    <th>Дата </th>
    <th>Имя поля</th>
    <th>Вариация</th>
    <th>Описание</th>
    <th>Вокабуляр</th>
    <%if ["QA","admin"].include? current_user.role %>
      <th>Востановить ?</th>
    <% end %>
    <th>Создано</th>
    <th colspan="9"></th>
  </tr>
  </thead>

  <tbody>
  <% @field_history.retailer.field_histories.where(field_id: @field_history.field_id).order(version: :desc).each_with_index do |field_history, index| %>
    <tr>
      <td>№ <%= field_history.version %></td>
      <td><%= field_history.updated_at %></td>
      <% if field_history.version != 1 && field_history.fields_title != (old_name = @field_history.retailer.field_histories.where(field_id: @field_history.field_id).select {|el| el.version == field_history.version - 1}.first.fields_title) %>
        <td style="color: #009966"><%= field_history.fields_title %><s style="color: #990033"><%= old_name %></s></td>
      <% else %>
        <td><%= field_history.fields_title %></td>
      <% end %>

      <% if field_history.version == 1 && field_history.variation_name == "General" %>
        <td><%= "Created field: #{field_history.variation_name}" %></td>
      <% else %> <!-- Тут возможно понадобится логика поиска и раграничения в новых именах -->
        <td><%= field_history.variation_name %></td>
      <%end %>

        <!--  Сравнить надо только вариации, дописать-->
      <% if field_history.version != 1 && field_history.variation_name !~ /Create new variation:/ && field_history.description != (old_desc = @field_history.retailer.field_histories.where(field_id: @field_history.field_id).select {|el| el.version == field_history.version - 1}.first.description) %>
        <td style="color: #009966"><%= field_history.description %><s style="color: #990033"><%= old_desc %></s></td>
      <% else %>
        <td><%= field_history.description %></td>
      <% end %>

      <% if field_history.version != 1 && field_history.vocabulary_name != (old_vocabulary_name = @field_history.retailer.field_histories.where(field_id: @field_history.field_id).select {|el| el.version == field_history.version - 1}.first.vocabulary_name) %>
        <td style="color: #009966"><%= field_history.vocabulary_name %><s style="color: #990033"><%= old_vocabulary_name %></s></td>
      <% else %>
        <td><%= field_history.vocabulary_name %></td>
      <% end %>
      <%if ["QA","admin"].include? current_user.role %>
        <td><%= (index == 0 || field_history.variation_name =~ /Create new variation:/) ? "Текущий контент" : (link_to 'Востановить контент', retailer_field_history_path(field_history), method: :put, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger") %></td>
      <% end %>
        <td><%= field_history.user.email  %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Назад', retailer_field_histories_path(@field_history.retailer_id), class: "btn btn-secondary" %>