config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # get "/field_histories", to: "field_histories#index"

  resources :tickets
  resources :vocabulary_histories

  resources :vocabularies
  resources :retailers do
    resources :field_histories
    resources :fields, shallow: true do
      resources :variations, shallow: true
    end#, shallow: true # частичная вложенность только для index create new
    resources :comments
  end
  root 'retailers#index'
end

app/models/retailer.rb
class Retailer < ApplicationRecord
  paginates_per 30

  validates :title, presence: { message: 'не может быть пустым'}, uniqueness: true

  belongs_to :user
  has_many :fields
  has_many :field_histories
  has_many :comments

  def self.search(search)
    where("title like '#{search}%'") if search
  end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_retailer, only: %i[ show edit update destroy ]
  before_action :check_role, only: %i[ new edit ]

  # GET /retailers or /retailers.json
  def index
    @retailers = params[:search].nil? ? Retailer.all.page(params[:page]) : Retailer.search(params[:search])
  end

  # GET /retailers/1 or /retailers/1.json
  def show
  end

  # GET /retailers/new
  def new
    @retailer = Retailer.new
  end

  # GET /retailers/1/edit
  def edit
  end

  # POST /retailers or /retailers.json
  def create
    @retailer = current_user.retailers.new(retailer_params)

    respond_to do |format|
      if @retailer.save
        format.html { redirect_to @retailer, notice: "Ретейлер был успешно создан." }
        format.json { render :show, status: :created, location: @retailer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retailers/1 or /retailers/1.json
  def update
    respond_to do |format|
      if @retailer.update(retailer_params)
        format.html { redirect_to @retailer, notice: "Ретейлер был успешно обновлен." }
        format.json { render :show, status: :ok, location: @retailer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retailers/1 or /retailers/1.json
  def destroy
    @retailer.destroy
    respond_to do |format|
      format.html { redirect_to retailers_url, notice: "Ретейлер был успешно удален." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retailer
      @retailer = Retailer.find(params[:id])
    end

    def check_role
      respond_to { |format| format.html { redirect_to retailers_path, alert: "У вас нету доступа к просмотру содержимого этой страницы" } } unless ["QA","admin"].include? current_user.role
    end

  # Only allow a list of trusted parameters through.
    def retailer_params
      params.require(:retailer).permit(:title)
    end
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_form.html.erb
<%= form_with(model: retailer) do |form| %>
  <% if retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(retailer.errors.count, "ошибка") %> препятствует сохранению:</h2>

      <ul>
        <% retailer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Название" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "#{retailer.new_record? ? 'Создать' : 'Изменить' }", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/retailers/edit.html.erb
<div class="container">
  <h1>Редактирование Ретейлера</h1>

  <%= render 'form', retailer: @retailer %>

  <%= link_to 'Показать', @retailer, class: "btn btn-secondary" %>
  <%= link_to 'Назад', retailers_path, class: "btn btn-secondary" %>
</div>

app/views/retailers/index.html.erb
<div class="container">
  <h1>Ретейлеры</h1>
  <%= link_to 'Новый ретейлер', new_retailer_path, class: "btn btn-primary" if ["QA","admin"].include? current_user.role %>
  <%= paginate @retailers unless params[:search] %>

  <table>
    <tbody>
      <% @retailers.each do |retailer| %>
        <tr>
          <td><%= retailer.title %></td>
          <td><%= link_to 'Показать', retailer, :"data-turbolinks" => "false", class: "btn btn-secondary" %></td>
          <td><%= link_to 'Изменить', edit_retailer_path(retailer), class: "btn btn-secondary" if ["QA","admin"].include? current_user.role %></td>
          <td><%= link_to 'История', retailer_field_histories_path(retailer), :"data-turbolinks" => "false", class: "btn btn-secondary" %></td>
          <td><%= link_to 'Удалить', retailer, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" if current_user.role.eql? "admin" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/retailers/new.html.erb
<div class="container">
  <h1>Новый ретейлер</h1>
  <%= render 'form', retailer: @retailer %>

  <%= link_to 'Назад', retailers_path, class: "btn btn-secondary" %>

</div>

app/views/retailers/show.html.erb
<span class="elem_with_icon">
  <i class="material-icons">book</i>
  <%= link_to 'История изменения полей', retailer_field_histories_path(@retailer) %></br>
</span>
<p>
  <strong>Ретейлеры: </strong>
  <%= @retailer.title %>
</p>

<% if ["QA","admin"].include?(current_user.role) %>
  <div class="row">
    <div class="col-sm-2">
      <%= Vocabulary.all.select {|el| el unless @retailer.fields.map {|rf| rf[:vocabulary_id]}.include? el[:id]}.empty? ? (link_to "Добавить новое слово в вокабуляр", new_vocabulary_path, class: "btn btn-primary") : (link_to "Добавить новое поле", new_retailer_field_path(@retailer), class: "btn btn-primary") %>
    </div>
  </div>
<% end %>

<% if (@retailer.fields.count > 0)  %>
  <strong>Поля:</strong>
  <div class="row caption content">
    <div class="col-sm-2">Наименование</div>
    <div class="col-sm-6">Описание</div>
    <div class="col-sm-2">Имя вокабуляра</div>
    <div class="col-sm-2"><%= ["QA","admin"].include?(current_user.role) ? "Удалить?" :  "Создание задачи" %></div>
  </div>

  <% @retailer.fields.each_with_index do |r_field, index| %>
    <div class="row content">
      <div class="col-sm-2"><%=["QA","admin"].include?(current_user.role) ? (link_to "#{index + 1}. #{r_field.title}", r_field, :"data-turbolinks" => "false", class: "btn btn-secondary") : "#{index + 1}. #{r_field.title}" %></div>
      <div class="col-sm-6">
        <% if r_field.variations.size > 1%>
          <select class="sel_desc result_hide_field_<%=index%>">
            <% r_field.variations.each_with_index do |var, r_index| %>
              <option id ="sel-<%=r_index%>" class="sel-<%=r_index%>"><%= var.name%></option>
            <% end %>
          </select>
        <%end %>
        <div >
          <% r_field.variations.each_with_index do |var, r_index| %>
            <div class="hide hide_result_<%=r_index%> result_hide_field_<%=index%>" ><%= var.description %></div>
            <% if ["QA","admin"].include?(current_user.role) %>
              <% if r_field.variations.size != 1 %>
                <span class="hide hide_result_<%=r_index%> result_hide_field_<%=index%>"><%= link_to 'Удалить вариацию', var, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" %></span>
              <% end %>
              <span class="hide hide_result_<%=r_index%> result_hide_field_<%=index%>"><%= link_to 'Изменить вариацию', edit_variation_path(var), class: "btn btn-secondary" %></span>
              <span class="hide hide_result_<%=r_index%> result_hide_field_<%=index%>"><%= link_to 'Добавить вариацию', new_field_variation_path(r_field), class: "btn btn-secondary" %></span>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-2"><%= r_field.vocabulary.name%></div>

      <% if ["QA","admin"].include? current_user.role %>
        <div class="col-sm-2"><%= link_to 'Удалить', r_field, method: :delete, data: { confirm: 'Вы уверены?'}, class: "btn btn-danger" %></div>
      <% else %>
        <div class="col-sm-2"><%= link_to 'Запросить задачу', controller: "tickets", method: :get, action: :new, data: { confirm: 'Создать задачу?'}, params: {field_id: r_field.id} %></div>
      <% end %>

    </div>
  <% end %>
<% else %>
  <strong>На текущий момент нет полей</strong>
<% end %>

  <div class="card-body">
    <% if @retailer.comments.empty? %>
      <p class="font-weight-bold comment_text">Будь первым кто оставит комментарий:</p>
    <% else %>
      <p class="font-weight-bold comment_text">Комментарии:</p>
    <% end %>
    <%= render @retailer.comments %>
    <%= form_with(model: [@retailer, @retailer.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'Новый коментарий' %>
        <%= f.text_area :body, class: 'form-control', required: "required" %>
      </div>
      <%= f.submit 'Отправить', class: 'btn btn-primary' %>
    <% end %>
  </div>

<%= link_to 'Назад', retailers_path, class: "btn btn-secondary" %>